
package net.bq;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FilmServiceService", targetNamespace = "http://service.org/", wsdlLocation = "http://localhost:8888/film?wsdl")
public class FilmServiceService
    extends Service
{

    private final static URL FILMSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FILMSERVICESERVICE_EXCEPTION;
    private final static QName FILMSERVICESERVICE_QNAME = new QName("http://service.org/", "FilmServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/film?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILMSERVICESERVICE_WSDL_LOCATION = url;
        FILMSERVICESERVICE_EXCEPTION = e;
    }

    public FilmServiceService() {
        super(__getWsdlLocation(), FILMSERVICESERVICE_QNAME);
    }

    public FilmServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILMSERVICESERVICE_QNAME, features);
    }

    public FilmServiceService(URL wsdlLocation) {
        super(wsdlLocation, FILMSERVICESERVICE_QNAME);
    }

    public FilmServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILMSERVICESERVICE_QNAME, features);
    }

    public FilmServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FilmServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FilmService
     */
    @WebEndpoint(name = "FilmServicePort")
    public FilmService getFilmServicePort() {
        return super.getPort(new QName("http://service.org/", "FilmServicePort"), FilmService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FilmService
     */
    @WebEndpoint(name = "FilmServicePort")
    public FilmService getFilmServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.org/", "FilmServicePort"), FilmService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILMSERVICESERVICE_EXCEPTION!= null) {
            throw FILMSERVICESERVICE_EXCEPTION;
        }
        return FILMSERVICESERVICE_WSDL_LOCATION;
    }

}
