
package net.bq;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FilmService", targetNamespace = "http://service.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FilmService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<net.bq.Film>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "search", targetNamespace = "http://service.org/", className = "net.bq.Search")
    @ResponseWrapper(localName = "searchResponse", targetNamespace = "http://service.org/", className = "net.bq.SearchResponse")
    @Action(input = "http://service.org/FilmService/searchRequest", output = "http://service.org/FilmService/searchResponse")
    public List<Film> search(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
